name: Package
on:
  release:
    types: [ created ]
jobs:
  package-android:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - uses: gradle/actions/setup-gradle@v4
      - run: |
          echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          chmod +x ./gradlew
      - name: Package android
        run: ./gradlew :application:assemble
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: android
          path: application/build/outputs/apk/debug/application-debug.apk
  package-windows:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - uses: gradle/actions/setup-gradle@v4
      - run: |
          echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          chmod +x ./gradlew
      - name: package windowsUberJar
        run: ./gradlew :application:packageUberJarForCurrentOS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: windowsUberJar
          path: application/build/compose/jars/*
      - name: package windowsAppImage
        run: ./gradlew :application:packageAppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: windowsAppImage
          path: application/build/compose/binaries/main/app/*
      - name: package windowsMsi
        run: ./gradlew :application:packageMsi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: windowsMsi
          path: application/build/compose/binaries/main/msi/*
      - name: package windowsExe
        run: ./gradlew :application:packageExe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: windowsExe
          path: application/build/compose/binaries/main/exe/*
  package-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - uses: gradle/actions/setup-gradle@v4
      - run: |
          echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          chmod +x ./gradlew
      - name: package linuxUberJar
        run: ./gradlew :application:packageUberJarForCurrentOS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: linuxUberJar
          path: application/build/compose/jars/*
      - name: package linuxAppImage
        run: ./gradlew :application:packageAppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: linuxAppImage
          path: application/build/compose/binaries/main/app/*
      - name: package linuxDeb
        run: ./gradlew :application:packageDeb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: linuxDeb
          path: application/build/compose/binaries/main/deb/*
      - name: package linuxRpm
        run: ./gradlew :application:packageRpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: linuxRpm
          path: application/build/compose/binaries/main/rpm/*
  package-macos:
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - uses: gradle/actions/setup-gradle@v4
      - run: |
          echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          chmod +x ./gradlew
      - name: package macosUberJar
        run: ./gradlew :application:packageUberJarForCurrentOS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: macosUberJar
          path: application/build/compose/jars/*
      - name: package macosDmg
        run: ./gradlew :application:packageDmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: macosDmg
          path: application/build/compose/binaries/main/dmg/*